[package]
name = "zkvyper-nix"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
base64 = "0.22.1"
genco = "0.17.9"
reqwest = "0.12.9"
reqwest-middleware = "0.3.3"
reqwest-retry = "0.6.1"
sha2 = "0.10.8"
tokio = { version = "1.41.1", features = ["full"] }
